services:
  app:
    build: .
    container_name: yolo_app
    expose:
      - "8000"  # only internal, Nginx will proxy

  nginx:
    image: nginx:latest
    container_name: yolo_nginx
    ports:
      - "8080:80"   # public → Nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

  locust:
    image: locustio/locust
    container_name: yolo_locust
    volumes:
      - ./locust:/mnt/locust   # mount whole folder (locustfile.py + test.jpg)
    working_dir: /mnt/locust   # run from inside mounted folder
    command: -f locustfile.py --host http://nginx
    ports:
      - "8089:8089"
    depends_on:
      - nginx
